### ISSUE TITLE
It just pops up an error every time

### ISSUE THREAD

**Issue by metype** [nathan/phosphorus#1210]
http://scratch.mit.edu/projects/145874066
http://phosphorus.github.io/#145874066

```
Error: HTTP 404: 
   at xhr.onload (https://phosphorus.github.io/phosphorus.js:224:9)
```

**Comment by coffeeboo** [comment]
![lol](https://file-odsynfiwiu.now.sh)

![wtf](https://pa1.narvii.com/5888/a7758379f45de8c29db4bd85bd40b51e4a7a5a9f_hq.gif)

**Comment by coffeeboo** [comment]
@Nathan Close this.

**Comment by nathan** [comment]
The project file doesn't exist. http://projects.scratch.mit.edu/project/145874066/get/
