### ISSUE TITLE
Scratch Kart Demo

### ISSUE THREAD

**Issue by nathan** [nathan/phosphorus#123]
- [x] Sounds

http://scratch.mit.edu/projects/908591/

**Comment by tjvr** [comment]
I can't get this project to load: <http://phosphorus.github.io/#908591>

I'm seeing 

> player.js:241 Error: XHR Error
>    at XMLHttpRequest.xhr.onerror (phosphorus.js:225)

...which I saw in a whole bunch of other issues, but assumed it was some sort of user internet error. (In actual fact, switching networks doesn't seem to help.)

**Comment by nathan** [comment]
I think Scratch finally fixed the thing where you can load other people's unshared projects.

**Comment by tjvr** [comment]
@nathan Certainly not for all projects; for example <https://scratch.mit.edu/projects/102361258/> still loads in phosphorus <http://phosphorus.github.io/#102361258>

**Comment by nathan** [comment]
Hmm, OK, weird. I just assumed that was because it was my project :P
