### ISSUE TITLE
Guys stahp using this program

### ISSUE THREAD

**Issue by boraini** [nathan/phosphorus#1653]
https://scratch.mit.edu/projects/306782239/embed . Just embed your projects.

**Comment by ynl1** [comment]
Embedding is slower.

**Comment by boraini** [comment]
> Embedding is slower.

Well, I guess Phosphorus just appeared to be a Javascript compiler for Scratch. I just say that people no longer need to tell people to run their graphics-intensive projects on Phosphorus, as the players aren't so much different now. It's still good for very low-end devices that doesn't support WebGL or its polyfills, or if you want to create some JS of a project with higher performance than the one outputted by Blockly used by Scratch 3 (I didn't see any performance differences, though, even worse in Phosphorus in some cases).

**Comment by ynl1** [comment]
Eh, They still are pretty different, there are some examples which run better on Phosphorus.
(like this one: https://scratch.mit.edu/projects/147495852/) Yes, they are pretty similar, but Phosphorus is faster.

**Comment by ynl1** [comment]
Besides, the embedded player is just as fast as the regular player, so there is no point to leaving a link to the embedded version.

**Comment by boraini** [comment]
Issue closed as my statement was heavily based on assumptions rather than actual code performance analysis.
