### ISSUE TITLE
Roads v6

### ISSUE THREAD

**Issue by nathan** [nathan/phosphorus#23]
- [x] Can't change selection using numbers or buttons
- [x] Buttons don't work (arrow keys?)
- [x] Bit slow
- [x] Cars and trains only move one tile, then stop
- [x] Occasionally hangs or puts cars off of their tracks
- [ ] Loading text persists

http://scratch.mit.edu/projects/10086980/
http://phosphorus.herokuapp.com/#10086980

**Comment by tjvr** [comment]
> Loading text persists

Why _does_ this happen?

**Comment by htmlgames** [comment]
The event on green flag clicked in tile sprite runs before the green flag clicked in loading msg sprite.
If you put a small delay after green flag clicked in tile sprite (say 1 sec) it clears the loading text on phosphorus. I suppose when using two+ green flag click events you cannot predict the order (maybe?)

**Comment by nathan** [comment]
> Why does this happen?

This is because phosphorus never forces a yield during atomic blocks.

A sprite broadcasts `Tiles Created` after an atomic block in the first frame of a green flag hat. The Stage broadcasts `Loading` in the first frame of a green flag hat. The normal behavior here is that `Tiles Created` is broadcast first, and then `Loading` is broadcast (since sprite green flag hats run before Stage green flag hats). However, the atomic block runs for so long that Scratch forces it to yield, which means that `Loading` gets broadcast first, and then in the next frame (or one of the next several frames) `Tiles Created` gets broadcast.

This is technically a problem with the original project, since if I had a really fast computer—fast enough that Scratch could run the entire atomic block within a half second—the loading text would persist in the Flash project player too.

**Comment by nathan** [comment]
All of the issues I mentioned other than the loading text persisting seem to have been fixed, so I'm closing this. Feel free to comment if I missed something.

**Comment by tjvr** [comment]
@nathan Thanks so much for this explanation. I've fixed the bug in the original project; it works great now! :-)
