### ISSUE TITLE
Disallow negative sizes

### ISSUE THREAD

**Issue by nathan** [nathan/phosphorus#291]
Sizes should be clamped at a small positive number.

http://scratch.mit.edu/users/nXIII/#comments-6199352

**Comment by tjvr** [comment]
Quoting <http://scratch.mit.edu/users/nXIII/#comments-6199352> for ease of reference:

> I think I may have found a small Phosphorus difference from Scratch - try "change size by -10" on a sprite until it goes negative. Scratch stops when it disappears; phosphorus allows it to go negative and it starts getting bigger again (probably turned inside-out - since the example I'm using is just a little blob for a star in a space game, it's hard to tell what is happening exactly.)

**Comment by tjvr** [comment]
Scratch bases the min/max size on the costume size.
```actionscript
		var origW:int = img.width;
		var origH:int = img.height;
		var minScale:Number = Math.min(1, Math.max(5 / origW, 5 / origH));
		var maxScale:Number = Math.min((1.5 * 480) / origW, (1.5 * 360) / origH);
```
Do we want to replicate this behaviour?

**Comment by trumank** [comment]
That's quite similar to keeping sprites on the stage so users don't lose their sprites in the editor. It's just an arbitrarily restriction. I don't think there is any reason to implement it as I haven't seen any broken projects because of it.
