### ISSUE TITLE
Page constantly reloads in Firefox

### ISSUE THREAD

**Issue by djdolphin** [nathan/phosphorus#302]
After the page loads in Firefox, it just reloads again immediately and absolutely nothing works.

**Comment by nathan** [comment]
CNR. What OS/Firefox version are you using?

**Comment by djdolphin** [comment]
Firefox 37.0a2 (Developer Edition) on Mac OS X 10.10.1

**Comment by nathan** [comment]
Firefox 35.0 on OS X 10.10.1 (the stable version) works fine.

**Comment by djdolphin** [comment]
Actually, it's a problem with HTTPS Everywhere redirecting http://phosphorus.github.io to https://phosphorus.github.io and https://phosphorus.github.io redirecting back to http://phosphorus.github.io.

**Comment by bleush38p** [comment]
Now that Scratch is https friendly, can phosphorus stop constantly redirecting back to http? It's frustrating to always have to turn HTTPS Everywhere off when using Phosphorus.
