### ISSUE TITLE
Project not loaded

### ISSUE THREAD

**Issue by sfederici** [nathan/phosphorus#303]
http://scratch.mit.edu/projects/2622353
http://phosphorus.herokuapp.com/#2622353

```
Error: XHR Error
    at XMLHttpRequest.xhr.onerror (http://phosphorus.github.io/phosphorus.js:224:21)
```

**Comment by nathan** [comment]
This is a 1.4 project, so phosphorus can't run it; the XHR error is because Scratch's API is broken and doesn't set CORS headers on 404 pages.

**Comment by sfederici** [comment]
As the Scratch website doesn't clarify if the project is 1.4 or 2.0, why not to add a specific warning in phosphorus? :)

**Comment by nathan** [comment]
https://github.com/nathan/phosphorus/issues/311
