### ISSUE TITLE
Sphere

### ISSUE THREAD

**Issue by sfederici** [nathan/phosphorus#314]
I'm not reporting a bug. I was just noticing that the colors look darker in the phosphorus player than in the Flash Scratch player.

http://scratch.mit.edu/projects/46901296/
http://phosphorus.herokuapp.com/#46901296
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36

**Comment by nathan** [comment]
They are—see https://github.com/nathan/phosphorus/pull/110#issuecomment-49642035
