### ISSUE TITLE
CORS Proxy died

### ISSUE THREAD

**Issue by nathan** [nathan/phosphorus#318]
:(

(project title fetching is currently broken)

**Comment by technoboy10** [comment]
You can use crossorigin.me if you want (I set it up)

**Comment by nathan** [comment]
I get an Application Error. I'm probably going to ask the ST to fix their APIs so I don't have to use a proxy at all.

**Comment by technoboy10** [comment]
Huh, that's weird, I'm not seeing that at all. Lemme fork and see if I find why that's coming up.

**Comment by technoboy10** [comment]
@nathan Fixed, looks like heroku didn't like www.
