### ISSUE TITLE
3D game of life

### ISSUE THREAD

**Issue by sfederici** [nathan/phosphorus#343]
The cubes are all blacks in phosphorus. Does phosphorus support the "pen shade" block?

http://scratch.mit.edu/projects/22364325/
http://phosphorus.herokuapp.com/#22364325
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36

**Comment by nathan** [comment]
CNR…? The cubes (i.e., dots) are almost exactly the same shade as in Scratch.

**Comment by trumank** [comment]
Actually, I looked at this yesterday and the cubes were legitimately black, unlike scratch. It was probably updated by the creator which then caused it to work correctly in phosphorus. I tried messing with the settings (press space) and I could not reproduce it, so I don't know what to conclude.

**Comment by sfederici** [comment]
The project has been changed (now you can chooose between cubes and dots, something that you couldn't do yesterday). Anyway, it works, so... nothing to add :)
