### ISSUE TITLE
mandelbrot

### ISSUE THREAD

**Issue by sfederici** [nathan/phosphorus#358]
There is no problem at all with this project. The phosphorus version is lightning speed. But I was wondering why the construnction phase (that is very slow in Scratch) doesn't appear at all in the phosphorus' Stage.

http://scratch.mit.edu/projects/53610528/
http://phosphorus.github.io/#53610528
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36

**Comment by nathan** [comment]
Scratch force-updates the screen every half-second during atomic blocks (`run without screen refresh`). phosphorus never updates the screen while an atomic block is running.

**Comment by sfederici** [comment]
Thanks a lot for the clarification.
