### ISSUE TITLE
Singularity copy

### ISSUE THREAD

**Issue by facepwn64** [nathan/phosphorus#360]
- [ ] Some sounds do not work.

http://scratch.mit.edu/projects/53601876/
http://phosphorus.github.io/#53601876
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36

**Comment by facepwn64** [comment]
For example, you can't hear the grenade explosion or the knifing sound. Otherwise, phosphorus is GREAT!

**Comment by tjvr** [comment]
See #260
