### ISSUE TITLE
Issue With A Project

### ISSUE THREAD

**Issue by yayestechlab** [nathan/phosphorus#362]
I've made a project that causes lag in many cases so am attempting to run it with phosphorus. However, my gravity code isn't working. This does seem like an amazing concept however.

http://scratch.mit.edu/projects/54132854/
http://phosphorus.github.io/#54132854
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.104 Safari/537.36

**Comment by trumank** [comment]
Caused by #22

**Comment by yayestechlab** [comment]
Just found that out after a bit of debug. Thanks for a quick response.
