### ISSUE TITLE
☁ FNaF 3 --Cloud Saves!-- ☁

### ISSUE THREAD

**Issue by MEGAPIE06** [nathan/phosphorus#371]
http://scratch.mit.edu/projects/55932084/
http://phosphorus.github.io/#55932084
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36

Many of the sound effects that are supposed to play don't play.

**Comment by tjvr** [comment]
Presumably relates to #260
