### ISSUE TITLE
http://scratch.mit.edu/projects/10128407/

### ISSUE THREAD

**Issue by cookiedragon234** [nathan/phosphorus#381]
At my school some websites are cyberoamed - one of these is the scratch website so the phosphorus games don't work.

http://scratch.mit.edu/projects/10128407/
http://phosphorus.github.io/#10128407
Mozilla/5.0 (Windows NT 6.1; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; rv:11.0) like Gecko

**Comment by 16140** [comment]
get an aproxy

**Comment by cookiedragon234** [comment]
Good answer! I already have... 
(except it got removed because we have to be "responsible")
