### ISSUE TITLE
Scratchthesia 1.5

### ISSUE THREAD

**Issue by SzAmmi** [nathan/phosphorus#382]
It lags with sounds blocks.

http://scratch.mit.edu/projects/56674150/
http://phosphorus.github.io/#56674150
Mozilla/5.0 (Windows NT 6.2; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0

**Comment by 16140** [comment]
try using chrome turbo mode

**Comment by SzAmmi** [comment]
Tried, it still lags :/

**Comment by SzAmmi** [comment]
Wow! You've fixed that! Works well on Mozilla Firefox. But... If I set tempo to e.g. 200 and save project with no block that sets the tempo, phosphorus sets tempo to default 60 (but I set tempo before!).
