### ISSUE TITLE
Raster 'ghosted' quad-fill performance test

### ISSUE THREAD

**Issue by sfederici** [nathan/phosphorus#385]
Is Phosphorus going to support the new alpha feature of the pen?

http://scratch.mit.edu/projects/61188592/
http://phosphorus.github.io/#61188592
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36

**Comment by trumank** [comment]
Already mentioned by #383

**Comment by 16140** [comment]
it works for me

**Comment by sfederici** [comment]
In phosphorus it is not "ghosted"
