### ISSUE TITLE
Typo in app.html

### ISSUE THREAD

**Issue by wizzwizz4** [nathan/phosphorus#395]
__A typo!__
On line 115 of app.html, a mysterious error to do with the window.title code.
Code has been removed accidently.
I was using Phosphorus when the Window title stopped changing to the project name
This isn't a major problem, but is easy to fix

**Comment by nathan** [comment]
[Huh?](https://github.com/nathan/phosphorus/blob/5e9a44f64d1f24972a9713d372e3d2aadca53eb7/app.html#L115)

**Comment by wizzwizz4** [comment]
Line 116, sorry!
And it has been fixed :+1:
Where's the close issue button?
