### ISSUE TITLE
Vector images are rasterized

### ISSUE THREAD

**Issue by ac8774** [nathan/phosphorus#450]
After looking at several issues (#294, #405, #194), it looks like vector images are being rasterized before being resized, so any vector costume over 100% size look pixelated, some more than others depending on the size.

**Comment by menasheh** [comment]
There's nothing wrong with that, but any time size changes, they should be re-rasterized at that size.  Right?

**Comment by ac8774** [comment]
Yes, they should, but they aren't. Look at the clouds in this project: http://phosphorus.github.io/#25217786 They were rasterized at normal size, then blown up about 5x.

**Comment by nathan** [comment]
Yes, they are, and they should be re-rasterized when they get too big.

**Comment by tjvr** [comment]
Is this related to #280? @nathan

**Comment by nathan** [comment]
Yes. #280 is a broken(ish) PR for re-rasterizing.
