### ISSUE TITLE
buddhabrot

### ISSUE THREAD

**Issue by sfederici** [nathan/phosphorus#489]
The project doesn't start.

http://scratch.mit.edu/projects/1757713/
http://phosphorus.github.io/#1757713
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36

**Comment by htmlgames** [comment]
No 'Access-Control-Allow-Origin' header is present on the requested resource for this project.

**Comment by trumank** [comment]
That's because it's a Scratch 1.4 project

**Comment by sfederici** [comment]
Right.
