### ISSUE TITLE
Spiral_Tree_Autumn_Edition

### ISSUE THREAD

**Issue by sfederici** [nathan/phosphorus#490]
After a little while it freezes.

http://scratch.mit.edu/projects/83947054/
http://phosphorus.github.io/#83947054
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36

**Comment by htmlgames** [comment]
Looks like the same issue as project 10002333. Canvas Arc method doesn't like -ve numbers

see here:

http://homepage.ntlworld.com/infinnerty/differences/UAT/itch/index.html#83947054

**Comment by nathan** [comment]
Fixed.
