### ISSUE TITLE
Blurred White Circles

### ISSUE THREAD

**Issue by sfederici** [nathan/phosphorus#507]
Different output.

http://scratch.mit.edu/projects/55610630/
http://phosphorus.github.io/#55610630
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36

**Comment by tjvr** [comment]
Is this the same bug as #508?

> phosphorus doesn't copy effects to clones.

**Comment by nathan** [comment]
Fixed the opacity, but the `WAIT 8 SECONDS STOP ALL` doesn't actually stop all.

**Comment by tjvr** [comment]
#511 was also complaining about `stop all`; maybe they're related?

**Comment by nathan** [comment]
Probably
