### ISSUE TITLE
Doesn't stop all scripts

### ISSUE THREAD

**Issue by DataPools** [nathan/phosphorus#511]
I have put a stop all block into my project, and it does not seem to take effect on other scripts (in other sprites). It only seems to affect the sprite that the ```stop all ``` block is in

http://scratch.mit.edu/projects/88483104/
http://phosphorus.github.io/#88483104
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36

**Comment by tjvr** [comment]
This project seems to work fine?

**Comment by DataPools** [comment]
Yes, I know, because I have modified it so it doesn't use any stop all block scripts. Try it out for yourself
