### ISSUE TITLE
Glitch with all projects

### ISSUE THREAD

**Issue by SuperScratch** [nathan/phosphorus#520]
I am not able to press any buttons such as full-screen GF and STOP

**Comment by DataPools** [comment]
You are probably on a browser where full screen is blocked.

**Comment by SuperScratch** [comment]
Well I am on chrome

**Comment by DataPools** [comment]
On Chrome the browser can sometimes block full screen try moving to a different browser and use phosphorus

**Comment by SuperScratch** [comment]
Im using chrome os :( I can not change browser

**Comment by SuperScratch** [comment]
FIXED
