### ISSUE TITLE
Negative pen size inaccuracy

### ISSUE THREAD

**Issue by quat1024** [nathan/phosphorus#523]
Presumably has something to do with how P renders pen sizes which are negative numbers?

I believe Scratch just sets the actual pen size to `max(1, desired_size)`, and Phosphorus seems to completely ignore requests to make the pen size negative. That may be totally wrong, and I'm sorry that I can't provide more details, i'm at school right now and Flash is always crashing on the stupid school computers for some reason.

\\\_(:smile:)_/

Anyway this breaks "circular logic" - notice how the orange circles completely vanish in P, where in Scratch they shrink and grow gently.

http://scratch.mit.edu/projects/78262318/
http://phosphorus.github.io/#78262318
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36

**Comment by tjvr** [comment]
b3ba0df fixed negative pen sizes, and was committed before this issue.
