### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by eliapplethetech** [nathan/phosphorus#544]
I can't hear sound.

**Comment by huftis** [comment]
I hear sound, but only on *some* projects. For example, on this, sound and music works fine:
http://phosphorus.github.io/#88929725
But on this, the sound doesn’t work at all
http://phosphorus.github.io/#94614557
They both seem to use .mp3 files for the sound, so I don’t know what the difference is.

**Comment by tjvr** [comment]
Presumably related to #260 ?

**Comment by Arinerron** [comment]
^

**Comment by Arinerron** [comment]
@nathan Is this fixed?

**Comment by nathan** [comment]
Yep
