### ISSUE TITLE
Line Shooter

### ISSUE THREAD

**Issue by Botboy3000** [nathan/phosphorus#549]
I've found an issue: That this project has sound on the scratch website but not on phosphorus. I have tested other projects that have sound and they work mostly except some sound files are still missing.

http://scratch.mit.edu/projects/97601475/
http://phosphorus.github.io/#97601475
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36

**Comment by TropicSapling** [comment]
Yeah recognize this issue on other projects as well :/

**Comment by tjvr** [comment]
Presumably related to #260
