### ISSUE TITLE
"pointing towards" something you're already at gives different results in Phosphorus

### ISSUE THREAD

**Issue by quat1024** [nathan/phosphorus#552]
1. go to Sprite2
2. point towards Sprite2
3. In Scratch we are now facing 90 degrees; in Phosphorus we face 0 degrees.

http://scratch.mit.edu/projects/98637658/
http://phosphorus.github.io/#98637658
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36

**Comment by htmlgames** [comment]
in phosphorus.js:
 atan2 requires y,x not x,y
also I noticed further up in the code, this.direction adds + 90, so it would make it like so

 this.direction = Math.atan2(y - this.scratchY, x - this.scratchX) * 180 / Math.PI + 90;

returns 90 (like the scratch project)
don't yet know if this is the final fix without more testing though.....

**Comment by tjvr** [comment]
FWIW, here's [the source](https://github.com/LLK/scratch-flash/blob/8832447ec321c68fe4cc1902c6f6640759995513/src/primitives/MotionAndPenPrims.as#L112-L121):

```actionscript
	private function primPointTowards(b:Block):void {
		var s:ScratchSprite = interp.targetSprite();
		var p:Point = mouseOrSpritePosition(interp.arg(b, 0));
		if ((s == null) || (p == null)) return;
		var dx:Number = p.x - s.scratchX;
		var dy:Number = p.y - s.scratchY;
		var angle:Number = 90 - ((Math.atan2(dy, dx) * 180) / Math.PI);
		s.setDirection(angle);
		if (s.visible) interp.redraw();
	}
```

**Comment by htmlgames** [comment]
Cheers, that's very useful. 
Makes me think that it should be using the sprite rather than the this object:

this.direction = 90 - ((Math.atan2(y - sprite.scratchY, x - sprite.scratchX) * 180) / Math.PI);

(Will need further testing)

**Comment by tjvr** [comment]
@htmlgames No, `sprite` here refers to what we're pointing _at_.

**Comment by tjvr** [comment]
Here's [Nathan's code](https://github.com/nathan/phosphorus/blob/b6c97ff912570c82a27116a0c1b99a3266533cb9/phosphorus.js#L1644-L1656):

```js
  Sprite.prototype.pointTowards = function(thing) {
    if (thing === '_mouse_') {
      var x = this.stage.mouseX;
      var y = this.stage.mouseY;
    } else {
      var sprite = this.stage.getObject(thing);
      if (!sprite) return 0;
      x = sprite.scratchX;
      y = sprite.scratchY;
    }
    this.direction = Math.atan2(x - this.scratchX, y - this.scratchY) * 180 / Math.PI;
    if (this.saying) this.updateBubble();
  };
```

Things to note here:

- `atan2(dx, dy)` is mathematically equivalent to `90 - atan2(dy, dx)`.
- Unlike [the other direction blocks](https://github.com/nathan/phosphorus/blob/b6c97ff912570c82a27116a0c1b99a3266533cb9/phosphorus.js#L2519-L2530), this function does not call `setDirection`. It relies instead on the output of `atan2()` being in the range (-π, π`).
- `atan2(0, 0)` is special-cased to return `0`.

I'm not sure which would be cheaper: changing the code to call `setDirection`, or special-casing `0,0`. Probably the latter, to avoid the function call.

**Comment by htmlgames** [comment]
Fix is good!
