### ISSUE TITLE
Guess Who!

### ISSUE THREAD

**Issue by htmlgames** [nathan/phosphorus#564]
Clicking on the face cards doesn't register correctly - on the scratch page you get a Yes / No response at the bottom.

http://scratch.mit.edu/projects/88075011/
http://phosphorus.github.io/#88075011
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36

**Comment by htmlgames** [comment]
looks like it's this bit of code in  phosphorus.js:
      return d[3] !== 0;

needs to be

return d[3] !== 100;

looks like it's getting the alpha channel data as some check to see if its 'ghosted', in which case the mouse click should not register as sprite is 'hidden'. Ghost value to make a sprite appear in this state is 100 (0 = visible)

**Comment by tjvr** [comment]
If you've found a fix, send a PR!

**Comment by nathan** [comment]
No, that's not a fix. That code is checking the alpha component of canvas image data, which is in the range 0–255, 0 being transparent.

**Comment by nathan** [comment]
The sprite is scale up to 200% and the mouse-touching code doesn't account for rotation or scale.

**Comment by nathan** [comment]
Brightness effect still doesn't work, but that's nothing new.
