### ISSUE TITLE
Control doen't work?

### ISSUE THREAD

**Issue by A-KouZ1** [nathan/phosphorus#565]
I've made a CHIP-8 project, eksploring the ROMs, needs some keys. and you can't select the roms

WHY???

Here:

http://scratch.mit.edu/projects/101101588/
http://phosphorus.github.io/#101101588
Mozilla/5.0 (Windows NT 6.1; rv:44.0) Gecko/20100101 Firefox/44.0

I can't.....

//CANNOT CONTROL IT! WITH ARROW KEY!//

**Comment by A-KouZ1** [comment]
Oh, Nevermind, I've solution, I should NOT use, key <any> pressed, because Phosphorus doesn't support it :\

**Comment by htmlgames** [comment]
you can implement any key in phosphorous.js like so:

    } else if (script[0][0] === 'whenKeyPressed') { // any
      if (script[0][1] == 'any') {
        for (var any = 127;any--;) { 
	  object.listeners.whenKeyPressed[any].push(f);
	}
      } else {
        object.listeners.whenKeyPressed[P.getKeyCode(script[0][1])].push(f);
      }
    } else if (script[0][0] === 'whenSceneStarts') {

**Comment by tjvr** [comment]
`any` key option first mentioned in #503
