### ISSUE TITLE
Disallow pen sizes <1

### ISSUE THREAD

**Issue by tjvr** [nathan/phosphorus#568]
@nathan why did b3ba0df explicitly not do this?

**Comment by tjvr** [comment]
Breaks #523

**Comment by tjvr** [comment]
Mentioned in #514 but I think the project is fixed now

 > There seems to be issues with setting the pen width to 0. In scratch is sets it to 1 instead, but in phosphorous it stays at its previous width perhaps?

**Comment by nathan** [comment]
> @nathan why did b3ba0df explicitly not do this?

Either a misreading of the source code or me thinking people might have a use case for pen sizes between 0 and 1.
