### ISSUE TITLE
Round pen sizes to int

### ISSUE THREAD

**Issue by tjvr** [nathan/phosphorus#570]
Scratch does this; presumably we should do too.

See <https://scratch.mit.edu/projects/102130425/> for a test case (also includes negative and <1 pen sizes).

Relates to #568

**Comment by tjvr** [comment]
Mentioned in #397

**Comment by tjvr** [comment]
Mentioned in #297

**Comment by nathan** [comment]
https://github.com/LLK/scratch-flash/blob/64fbd33b921ca74248c374bd8f08272f556edce9/src/scratch/ScratchSprite.as#L264

I think the reason I was avoiding this is that it's slow(er than not rounding).

**Comment by tjvr** [comment]
I thought that might be it :P

**Comment by tjvr** [comment]
Some projects actually look smoother with fractional pen sizes, eg. <https://scratch.mit.edu/projects/104715050/#comments-57760526>. I vote we close this. :-)
