### ISSUE TITLE
Trying to embed Phosphorus

### ISSUE THREAD

**Issue by colt05** [nathan/phosphorus#587]
Hi!
I am trying to embed phosphorus into [a webpage](https://github.com/colt05/Random-Scratch-Project/blob/gh-pages/usephosphorus.html) on Github Pages.
It gives me this error:

```
Error: XHR Error
    at XMLHttpRequest.xhr.onerror (http://phosphorus.github.io/phosphorus.js:225:21)
```

Why is this happening?
Thanks!

**Comment by trumank** [comment]
The majority of projects with IDs < 10 million are Scratch 1.4 projects, which phosphorus doesn't support.

**Comment by colt05** [comment]
oh ok.
