### ISSUE TITLE
Borderline AMV *WIP*

### ISSUE THREAD

**Issue by AmayaLarae** [nathan/phosphorus#599]
http://scratch.mit.edu/projects/103297610/
http://phosphorus.github.io/#103297610
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36

There's no sound for this project, please fix!

**Comment by tjvr** [comment]
See #260

**Comment by AmayaLarae** [comment]
Thanks
