### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by codekrafter** [nathan/phosphorus#611]
http://scratch.mit.edu/projects/1678269
http://phosphorus.github.io/#1678269

```
Error: XHR Error
    at XMLHttpRequest.xhr.onerror (http://phosphorus.github.io/phosphorus.js:225:21)
```

**Comment by edward789121** [comment]
🤔 well... Phosphorus has to be able to run every 2.0 project :P and I don't know how it is possible to be able to run any project there is. So maybe the phosphorus server skipped a URL.

**Comment by bleush38p** [comment]
Phosphorus doesn't support 1.4 projects (#311). If you want to run this project in phosphorus, you can remix it in Scratch, which will update it to the 2.0 file format.

You can actually see in the network log that the Scratch player requests the 2.0 version of the project, and, failing to find that, falls back to loading the pre-2.0 `.sb`.
![image](https://cloud.githubusercontent.com/assets/7422958/15488708/a46a3bc0-211e-11e6-90bb-f38650a7ccc4.png)

**Comment by edward789121** [comment]
@bleush38p 
(:
