### ISSUE TITLE
Fruit Dash 2

### ISSUE THREAD

**Issue by crasyleg73** [nathan/phosphorus#615]
I do not know if unshared projects work.... but they work on my computer.
Variable sliders will move whenever the mouse is down and touching them.
It should only move if you clicked the mouse down when you were touching the slider.

Also the vector art is cut off for some reason.

In this project, you can press x to start running things.

http://scratch.mit.edu/projects/103113133/
http://phosphorus.github.io/#103113133
Mozilla/5.0 (X11; CrOS x86_64 7834.70.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

**Comment by tjvr** [comment]
I think this is a duplicate.
