### ISSUE TITLE
Sense OS Issue 2

### ISSUE THREAD

**Issue by eitan3085** [nathan/phosphorus#632]
NOW IT WONT EVEN UPDATE TO THE LATEST VERSION OF THE PROJECT I JUST EDITED SOME THINGS AND WHEN I TRY TO RUN IT IN PHOSPHORUS THE THINGS I ADDED AREN'T THERE ONLY THE THINGS I ADDED RIGHT AFTER I CREATED THE PROJECT

**Comment by onx-design** [comment]
Use [Sulforous Player](https://sulfurous.aau.at) instead

**Comment by eitan3085** [comment]
Forgot to close this

**Comment by onx-design** [comment]
Lol

**Comment by onx-design** [comment]
Makes SENSE
