### ISSUE TITLE
http://scratch.mit.edu/projects/114638386/

### ISSUE THREAD

**Issue by TotallyOriginal** [nathan/phosphorus#654]
Loading this project gets stuck loading at about 98%

http://scratch.mit.edu/projects/114638386/
http://phosphorus.github.io/#114638386
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by htmlgames** [comment]
Wow - this is genius!

**Comment by nathan** [comment]
Fixed.
