### ISSUE TITLE
Embed converted scratch project without internet access

### ISSUE THREAD

**Issue by mverissi** [nathan/phosphorus#665]
Hi, maybe this is a dumb question, but...

I'd like to convert a Scratch project and convert it to Javascript, as Phosphorus does; however, I wonder if it would be possible to embed this project in an Epub 3 file, so that I could open it and have the converted Scratch project run on the ebook when it is oppened by the reader (GitDen, for example) but without the need for internet access. Is it possible?

Best regards,

Marcos

**Comment by edward789121** [comment]
you can get some at https://phosphorus.github.io/embed.js?id={ID}&auto-start=true&light-content=false

**Comment by htmlgames** [comment]
Possible - however you may need to store the project within the javascript (maybe in base64 format) if you don't want to download over the internets

**Comment by nathan** [comment]
No.

**Comment by htmlgames** [comment]
??
That's how I did it for baking projects into an apk. 
I Stored the downloaded project.sb2 (which we know is a basically a zip) then base64 encoded file as a javascript var and convert it to a blob object and use that - works a treat as is totally offline solution.
