### ISSUE TITLE
http://scratch.mit.edu/projects/116194161/

### ISSUE THREAD

**Issue by tomrow** [nathan/phosphorus#671]
particles fall sideways instead of downwards on the scratch flash player

http://scratch.mit.edu/projects/116194161/
http://phosphorus.github.io/#116194161
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by htmlgames** [comment]
Looks like it could be something to do with the default direction for each particle?

**Comment by nathan** [comment]
Fixed.
