### ISSUE TITLE
http://scratch.mit.edu/projects/114583855/

### ISSUE THREAD

**Issue by MrPotatoCake** [nathan/phosphorus#673]
- [x] The text engine, soul sprite, health numerical readout, level readout, and the enemy damage numerical   readout, and certain costumes, are all invisible.
- [x] Plus, some of the sound effects and music doesn't work

http://scratch.mit.edu/projects/114583855/
http://phosphorus.github.io/#114583855
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by iiLucky** [comment]
Same here.

**Comment by PortPixel** [comment]
The reason for the the music not working is that Phosphorus can only play some sound types in certain browsers, as some (like chrome) cannot decode the sound files. The reason for the sprites not showing is that phosphorus cannot currently correctly display all graphic effects, causing the sprites to be invisible.

**Comment by nathan** [comment]
Looks like all the sprites are there for me? If there's still an issue, let me know. Sound definitely works now.
