### ISSUE TITLE
Epic Ninja v1.12

### ISSUE THREAD

**Issue by csf30816** [nathan/phosphorus#683]
When trying to play this game The graphics (like the ninjas and the title) do not load.

http://scratch.mit.edu/projects/21554369/
http://phosphorus.github.io/#21554369
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.146 Safari/537.36

**Comment by nathan** [comment]
Fixed

**Comment by csf30816** [comment]
Yeah, thanks. I created Scratch order that fixed this too...

**Comment by csf30816** [comment]
*ScratchViewer sorry autocorrect/on phone.
