### ISSUE TITLE
Circle Rebound - using clones

### ISSUE THREAD

**Issue by CrazyLegs66** [nathan/phosphorus#688]
Something is wrong with the drawing co-ordinates.
This project should start by exploding a circle of clones from 0,0 but they form a cross instead; rebounding way too early.

http://scratch.mit.edu/projects/20497702/
http://phosphorus.github.io/#20497702
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

**Comment by htmlgames** [comment]
http://htmlgames.github.io/htmlgames/differences/UAT/itchy/index.html#20497702

**Comment by nathan** [comment]
Fixed.
