### ISSUE TITLE
Epic Ninja v1.12

### ISSUE THREAD

**Issue by Harrytheawesome** [nathan/phosphorus#689]
http://scratch.mit.edu/projects/21554369/
http://phosphorus.github.io/#21554369
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36

Epic Ninja's ninjas aren't showing up.

**Comment by htmlgames** [comment]
http://htmlgames.github.io/htmlgames/differences/UAT/itchy/index.html#21554369

**Comment by nathan** [comment]
Fixed.
