### ISSUE TITLE
SideScroller not working with Package

### ISSUE THREAD

**Issue by gatzke** [nathan/phosphorus#691]
Package does not seem to work.  Tried every combination.

Glad to see the player up and running again with vectors!  Nice work.

http://scratch.mit.edu/projects/120171080/
http://phosphorus.github.io/#120171080
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

**Comment by gatzke** [comment]
Embed seems to have similar issues.  Using Chrome win 10.

**Comment by htmlgames** [comment]
Package requires the fix that Nathan made to index.html (canvg stuff), be also applied to app.html
Don't know about embed though... maybe similar.

**Comment by nathan** [comment]
Fixed

**Comment by gatzke** [comment]
Thanks!  You are awesome and appreciated.
