### ISSUE TITLE
Double Snake (Test) OP Backup AI Snake

### ISSUE THREAD

**Issue by Harrytheawesome** [nathan/phosphorus#693]
http://scratch.mit.edu/projects/120395395/
http://phosphorus.github.io/#120395395
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36

Won't Load. If it did load there's probably be a run without screen refresh, though.

**Comment by nathan** [comment]
Appears to work fine. If there's still an problem, please share the project and open a new issue.
