### ISSUE TITLE
3-D gem with shading

### ISSUE THREAD

**Issue by Sir-Cool** [nathan/phosphorus#697]
This project works really well on phosphorus, however if I package it then when you click the space bar the torch doesn't appear, whereas if you just use phosphorus as it is then clicking space shows it as normal.

http://scratch.mit.edu/projects/125102161/
http://phosphorus.github.io/#125102161
Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/51.0.2704.79 Chrome/51.0.2704.79 Safari/537.36

**Comment by trumank** [comment]
Fixed in PR #698
