### ISSUE TITLE
Sonic: Doomsday MOBILE PORT!

### ISSUE THREAD

**Issue by TheNotch2112** [nathan/phosphorus#701]
The game would not fully load, but it has fully loaded every other time I've played this before-hand.

http://scratch.mit.edu/projects/126791845
http://phosphorus.github.io/#126791845

```
Error: XHR Error
    at XMLHttpRequest.xhr.onerror (http://phosphorus.github.io/phosphorus.js:225:21)
```

**Comment by nathan** [comment]
Clear your cache? Works fine for me.
