### ISSUE TITLE
PET THE DOG!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by DJEwan** [nathan/phosphorus#702]
No sound =/

http://scratch.mit.edu/projects/127118449/
http://phosphorus.github.io/#127118449
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2899.0 Safari/537.36

**Comment by PortPixel** [comment]
Phosphorus only has sound in Safari.

**Comment by PortPixel** [comment]
The reason for this is that some browsers (like chome and firefox) cannot decode the media files that scratch store sound in. This has been mentioned many times before, so please check other issues to see if yours is something not mentioned before, before you post.
