### ISSUE TITLE
Can't embed Phosphorus projects in https webpages

### ISSUE THREAD

**Issue by sfederici** [nathan/phosphorus#704]
I can't embed content from, for example, http://phosphorus.github.io/app.html?id=11397100&turbo=false&full-screen=true in my website that uses HTTPS protocol, as the phosphorus.github.io site doesn't use HTTPS enforcement. 

The new security settings in Apache servers enforce that all HTTPS pages (the pages I use to provide content to my students) cannot embed content from unsecure HTTP pages.

HTTPS enforcement can be setup in github.io websites by following this simple procedure:
- navigate to the main page of the repository.
- under your repository name, click Setting button.
- under "GitHub Pages", select Enforce HTTPS.

Do you think this can be done for your phosphorus.github.io repository?

**Comment by nathan** [comment]
No. Scratch's resource loading is broken over HTTPS.

**Comment by sfederici** [comment]
That is exactly what I was hoping it wasn't that way. Thanks for letting me know.
