### ISSUE TITLE
[UNRELEASED] Amber OS Build 1603

### ISSUE THREAD

**Issue by Wasserboy08** [nathan/phosphorus#714]
Project dosent load just stucks at 100%
![image](https://cloud.githubusercontent.com/assets/22521667/20280331/6648263c-aaac-11e6-84c9-263b57a58c2a.png)

http://scratch.mit.edu/projects/99503483/
http://phosphorus.github.io/#99503483
Mozilla/5.0 (Windows NT 6.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

**Comment by TheUltimatum** [comment]
It does this with a few of my projects as well...

**Comment by nathan** [comment]
Fixed
