### ISSUE TITLE
Convert to .swf

### ISSUE THREAD

**Issue by GreenBayRules** [nathan/phosphorus#715]
Is it possible to convert a Scratch Project to .swf?

**Comment by TheUltimatum** [comment]
Quite possible but why would you do it here?

**Comment by nathan** [comment]
Yes.

**Comment by GreenBayRules** [comment]
How do I though.

Sent from my iPhone

On Nov 15, 2016, at 8:23 PM, Nathan <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes.

-
