### ISSUE TITLE
add to github page.

### ISSUE THREAD

**Issue by GreenBayRules** [nathan/phosphorus#718]
I want to add a scratch project to my github page, without the "Scratch Stuff" on it. Your phosphorus works perfectly! Except for one problem, github doesn't let me use iframes! Any suggestions?

**Comment by Heath123** [comment]
This isn't an issue.

**Comment by CosmicWebServices** [comment]
Well try `<iframe href="<insert link here>"></iframe>`

**Comment by nathan** [comment]
Probably because GitHub pages now forces https and phosphorus explicitly avoids https because it used to cause problems. I'll look into this and see if I can allow it.

**Comment by nathan** [comment]
phosphorus is now https-only, so if that was the problem it should be fixed now. Let me know if you're still having issues embedding phosphorus
