### ISSUE TITLE
Slider not working?

### ISSUE THREAD

**Issue by bjskistad** [nathan/phosphorus#723]
I ran an [example raycasting project](http://phosphorus.github.io/#130837209) on Phosphorus, and it will not allow me to adjust the slider for the detail of the cast. Is this an issue in all projects or just this one?

**Comment by nathan** [comment]
Works fine for me.

**Comment by nathan** [comment]
Works fine for me. Setting the resolution to 0 freezes the whole project on both Scratch and phosphorus, but Scratch interrupts hung atomic blocks every half-second and phosphorus (by design) does not.
