### ISSUE TITLE
Dot (a platformer) ALPHA v 0.3

### ISSUE THREAD

**Issue by LongLostPal** [nathan/phosphorus#729]
http://scratch.mit.edu/projects/132914188/
http://phosphorus.github.io/#132914188
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
My very laggy scratch project is a scrolling platformer.  I transferred it to phosphorus and, it indeed was less laggy, but the game would not scroll.

**Comment by PortPixel** [comment]
It appears to work for me

**Comment by nathan** [comment]
CNR
