### ISSUE TITLE
Wrong instrument in clones

### ISSUE THREAD

**Issue by mobluse** [nathan/phosphorus#730]
This project should use guitar (and does so on Scratch), but here on Phosphorus it uses piano. The instrument you set in the original sprite should be copied to the clones if they are created after the instrument was set. I have tested to set the instrument in "when I start as a clone", but then there was no sound at all.

http://scratch.mit.edu/projects/134676132/
http://phosphorus.github.io/#134676132
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36

**Comment by nathan** [comment]
Fixed
