### ISSUE TITLE
Supre Mario Kartt Ate v1 (remastered!)

### ISSUE THREAD

**Issue by ehamawy** [nathan/phosphorus#731]
No sound

http://scratch.mit.edu/projects/128261332/
http://phosphorus.github.io/#128261332
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36

**Comment by PortPixel** [comment]
Phosphorus only plays sound in certain browsers
