### ISSUE TITLE
Steam-powered platforms (platformer game)

### ISSUE THREAD

**Issue by caboos3** [nathan/phosphorus#733]
http://scratch.mit.edu/projects/76528386/
http://phosphorus.github.io/#76528386
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by caboos3** [comment]
this isn't just for this game, I was just using this game to test, but, there's no sound whatsoever in phosphorus games which makes it not such a good idea to use for games. It would be really good for me if you could include the sound. thanks
                                                            ollie

**Comment by PortPixel** [comment]
Phosphorus only plays sound in certain browsers, as some (like chrome) cannot decode the sound files.

**Comment by caboos3** [comment]
oh. Thankyou for clearing this up. It would be useful if you could somehow
enable sound compatibility for chrome, as it is the most widely used
browser.

**Comment by PortPixel** [comment]
It is not as easy as simply 'enabling' it, see #736

**Comment by caboos3** [comment]
Sorry yeah I know that it's not that simple. I used the wrong word. I meant
to fix this issue by using a different way to play the sounds through the
browser. Also, It doesn't seem to work in IE either (at least win 7 IE) so
I thought that might be useful for you to know as you only before mentioned
chrome and firefox.
