### ISSUE TITLE
J

### ISSUE THREAD

**Issue by vcxz2323r** [nathan/phosphorus#734]
http://scratch.mit.edu/projects/183045973
http://phosphorus.github.io/#183045973

```
Error: XHR Error
    at XMLHttpRequest.xhr.onerror (http://phosphorus.github.io/phosphorus.js:225:21)
```

**Comment by PortPixel** [comment]
That appears to be an error either to do with your internet connection, or the Scratch Website, not phosphorus

**Comment by nathan** [comment]
Original project is gone/inaccessible.
