### ISSUE TITLE
Audio not working and sprites issue

### ISSUE THREAD

**Issue by TheSecretPenguin** [nathan/phosphorus#736]
Seems that audio does not run in projects, and certain sprites not closing when told to.

**Comment by Tymewalk** [comment]
I've tested the audio glitch with several other projects. This happens on all of them.

Firefox 50.0 running on Ubuntu 14.04.

**Comment by TheSecretPenguin** [comment]
Is there a way to fix the issue?

**Comment by nathan** [comment]
Duplicate of #260
