### ISSUE TITLE
Another Problem With Space Simulator 2

### ISSUE THREAD

**Issue by ScratcherAwesomeMinecraft2005** [nathan/phosphorus#738]
http://scratch.mit.edu/projects/138105317/
http://phosphorus.github.io/#138105317
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:48.0) Gecko/20100101 Firefox/48.0

serious lag

**Comment by PortPixel** [comment]
This is not an issue with phosphorus

**Comment by nathan** [comment]
Duplicate of https://github.com/nathan/phosphorus/issues/737
