### ISSUE TITLE
Paper Minecraft v11.3 (Minecraft 2D)

### ISSUE THREAD

**Issue by SamhuffyX4** [nathan/phosphorus#740]
This doesn't create any sound.

**Comment by PortPixel** [comment]
Phosphorus only plays sound in certain browsers. This has been said before many times, so please look at past issues before adding another one.

**Comment by PortPixel** [comment]
The reason for this is that some browsers (like chome and firefox) cannot decode the media files that scratch store sound in. This has been mentioned many times before, so please check other issues to see if yours is something not mentioned before, before you post.

**Comment by nathan** [comment]
Please include a link to the project (?)
