### ISSUE TITLE
error

### ISSUE THREAD

**Issue by niansa** [nathan/phosphorus#742]
http://scratch.mit.edu/projects/185346
http://phosphorus.github.io/#185346

```
IO.load/xhr.onerror@http://phosphorus.github.io/phosphorus.js:225:21

```

**Comment by PortPixel** [comment]
That appears to be an error either to do with your internet connection, or the Scratch Website, not phosphorus

**Comment by nathan** [comment]
This is a 1.4 project, which we don't support. (https://github.com/nathan/phosphorus/issues/311)
