### ISSUE TITLE
EFL 17 Pack Opener v Scratchi

### ISSUE THREAD

**Issue by rautekuvchvat** [nathan/phosphorus#748]
http://scratch.mit.edu/projects/140105613/
http://phosphorus.github.io/#140105613
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

when i put this project on this site it doesnt load, other projects do

**Comment by nathan** [comment]
That's a 1.4 project, which we don't support. (#311)
