### ISSUE TITLE
SVGs with no xmlns are unsupported

### ISSUE THREAD

**Issue by tjvr** [nathan/phosphorus#753]
tosh's default sprite doesn't specify an XML namespace:

```svg
<svg width='25px' height='20px'><path style='fill:#007de0;stroke:#033042;stroke-width:1;stroke-linejoin:round;' d='M 0,0 20,8 0,16 6,8 Z' /></svg>
```
aac22d5 means these SVGs now fail to load (`Cannot set property 'visibility' of undefined`).

Entirely my fault of course, and obviously I'll go fix that; but unfortunately I can't fix projects which were already shared! :)

[example project](https://phosphorus.github.io/#104715050)

**Comment by tjvr** [comment]
Thanks for the rest of the changes; they mean I don't have to patch phosphorus any more :D

**Comment by nathan** [comment]
Does Scratch ever do this?

**Comment by tjvr** [comment]
> Does Scratch ever do this?

No, I don't think so.

**Comment by nathan** [comment]
I can't think of a way to do this without either parsing the root element by hand and adding an xmlns attribute or trying to parse it twice (once as HTML, once as xml).
