### ISSUE TITLE
circle wars - Arcade Edition

### ISSUE THREAD

**Issue by arloclc** [nathan/phosphorus#772]
The variables always go to the front of the other sprites even though, in Scratch, they are programmed not to.

https://scratch.mit.edu/projects/139049542/
https://phosphorus.github.io/#139049542
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by nathan** [comment]
Wontfix—this happens in the 3d flash player too. (Press Ctrl+M in the editor)
